param(
    [string] $ApiBaseUrl = "http://127.0.0.1:8000"
)

$ErrorActionPreference = "Stop"

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if ($ApiBaseUrl -notmatch "^https?://") {
    throw "URL debug harus diawali http:// atau https://"
}

$javaHome = Join-Path $repoRoot "tools\jdk-21"
$androidHome = Join-Path $repoRoot "Android\Sdk"
$frontendRoot = Join-Path $repoRoot "frontend"
$androidRoot = Join-Path $frontendRoot "android"
$configPath = Join-Path $frontendRoot "app-config.js"
$debugApk = Join-Path $androidRoot "app\build\outputs\apk\debug\app-debug.apk"
$localDebugApk = Join-Path $androidRoot "app\build\outputs\apk\debug\app-debug-local.apk"

if (-not (Test-Path (Join-Path $javaHome "bin\java.exe")) -or -not (Test-Path (Join-Path $androidHome "platforms\android-35"))) {
    & (Join-Path $repoRoot "install-android-toolchain.bat")
    if ($LASTEXITCODE -ne 0) {
        throw "Gagal menyiapkan Android toolchain."
    }
}

$env:JAVA_HOME = $javaHome
$env:ANDROID_HOME = $androidHome
$env:ANDROID_SDK_ROOT = $androidHome
$env:Path = "$javaHome\bin;$androidHome\cmdline-tools\latest\bin;$androidHome\platform-tools;$env:Path"

$originalConfig = Get-Content -LiteralPath $configPath -Raw

try {
    $normalizedUrl = $ApiBaseUrl.TrimEnd("/")
    @"
window.BYRONZ_CONFIG = Object.freeze({
  // Debug build generated by build-android-debug-local.bat
  // For release builds, run set-byronz-api.bat with a public HTTPS backend.
  apiBaseUrl: "$normalizedUrl"
});
"@ | Set-Content -LiteralPath $configPath -Encoding UTF8

    Push-Location $frontendRoot
    try {
        & npm.cmd run build
        if ($LASTEXITCODE -ne 0) {
            throw "Frontend build gagal."
        }

        & npx.cmd cap sync android
        if ($LASTEXITCODE -ne 0) {
            throw "Capacitor sync Android gagal."
        }
    }
    finally {
        Pop-Location
    }

    Push-Location $androidRoot
    try {
        & .\gradlew.bat assembleDebug
        if ($LASTEXITCODE -ne 0) {
            throw "Gradle assembleDebug gagal."
        }
    }
    finally {
        Pop-Location
    }

    Copy-Item -LiteralPath $debugApk -Destination $localDebugApk -Force
    Write-Host ""
    Write-Host "APK debug lokal Byronz siap:"
    Write-Host $localDebugApk
}
finally {
    Set-Content -LiteralPath $configPath -Value $originalConfig -Encoding UTF8
}
